### ISSUE TITLE
Save icon request

### ISSUE THREAD

**Issue by pstreef** [vaadin/vaadin-icons#26]
Hi guys,

I'm missing the rather basic save (floppy disk) icon. Is there a reason this was not added and if not, could it perhaps be added?

Peter

**Comment by Saulis** [comment]
Hey there!

Unfortunately, we are not currently planning to add the "floppy disk" icon to `vaadin-icons`. 

`<iron-icons>` seems to contain an icon for this, called `icons:save`. 

If you don't want to import the whole `iron-icons` iconset, you can create your own like this: https://jsfiddle.net/Saulis/b9upvp7c/

**Comment by pstreef** [comment]
I currently use the (deprecated) Font awesome icon. Which is fine for now.

Thanks for the answer though!

**Comment by jouni** [comment]
Hi Peter! Thanks for asking. I’ll check with the author of the icons if he could draw that. 

Personally, I think the floppy icon starts to be very outdated, and I would not use it anymore to indicate saving in modern apps. But I do understand that it might be a good fit in some situations, still.

**Comment by pstreef** [comment]
I do agree Jouni, but what else is there? Most people know what it means even though they might not have ever seen a floppy before.

**Comment by jouni** [comment]
Right, it is kinda funny how we’ve made the association so strong even though many people have no idea what the icons represents :)

I would say that the tendency in modern apps is to move away from having any explicit save buttons, and any changes are saved in the background automatically. For the situations when you need an explicit save/submit button, I would make leave it without an icon.

Since you mentioned you’re using the deprecated FA icon, I assume you’re using Vaadin Framework 8, right? Just a small heads-up to @Saulis, that this icon library has more users than just Polymer devs ;) (and the `<iron-icons>` instructions don’t apply for Vaadin Framework).

**Comment by jouni** [comment]
Also, the author, @Jaska79, said basically the same as I did, that the floppy icon is such an old metaphor and we are not planning on adding that to our icon set.

So I think it’s best for you if you keep using FA for this need. If you don’t want to depend on the deprecated package, you can use this community add-on for Font Awesome: https://vaadin.com/directory#!addon/fontawesomelabel

**Comment by pstreef** [comment]
I guess devs who keep using the floppy save icon actually are the reason for this strong association in the first place. So I think you are right. I too will drop using the icon.

Thanks for your input Jouni!

fyi, I'm in the process of migrating to V8

**Comment by leluna** [comment]
I don't think UI developpers should be forced by a framework to join the "mission" of deprecating floppy disk as a save icon. The most important thing for me is what USER wants to see, or how they can find the right button as fast as possible. In my case, most of our users don't want to confused by the cloud/hard drive/database icon. They mostly don't care, but simply wish a floppy disk icon that symbolizes "save, I don't care how".

**Comment by Enerccio** [comment]
Exactly, I am very surprised that there is no save icon....

**Comment by jouni** [comment]
To make it easier to use your own icons in a Vaadin app, there’s an [icon set generator](https://vaadin.com/docs/latest/components/icons#icon-set-generator) in the docs ([currently in preview](https://pr-1612.dcmp4ajsd49kq.amplifyapp.com/components/icons/#icon-set-generator)), which makes it easier to incorporate your own icons in an app. You can then upload the Font Awesome [floppy-disk icon](https://github.com/FortAwesome/Font-Awesome/blob/6.x/js-packages/%40fortawesome/fontawesome-free/svgs/solid/floppy-disk.svg) there.
