### ISSUE TITLE
search-plus and search-minus are switched

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-icons#37]
The unicode characters for the the search-plus and search-minus icons are switched.

The fix is either to generate the fonts again, where the SVG's are swapped, or to fix the JSON with the correct unicode character values.

**Comment by jouni** [comment]
If we want to merge this external PR (https://github.com/vaadin/vaadin-icons-addon/pull/11), we should fix the JSON and not touch the fonts.

I guess it makes no difference how we fix this, it will cause some apps to break, if developers are using the wrong unicode/Enum in their apps. `iron-icon` usage is unaffected, as it uses the SVG versions directly and not the font.

**Comment by Haprog** [comment]
This fix is now included in [v4.2.2](https://github.com/vaadin/vaadin-icons/releases/tag/v4.2.2)
