### ISSUE TITLE
some usefull FontAwesome icons are missing

### ISSUE THREAD

**Issue by arabedini** [vaadin/vaadin-icons#40]
**VIDEO_CAMERA**

**Comment by manolo** [comment]
@jouni do you know what should be the content of vaadin collection? does it need to have same staff than font-awesome?

**Comment by jouni** [comment]
No, we don’t have to include all the same icons as in Font Awesome. That, of course, would make it easier for people to switch.

**Comment by jouni** [comment]
@arabedini, isn’t the `movie` icon close enough: https://github.com/vaadin/vaadin-icons/blob/master/assets/svg/movie.svg

**Comment by arabedini** [comment]
@jouni, you can user an icon like this for better zoom: https://image.flaticon.com/icons/svg/28/28639.svg

**Comment by jouni** [comment]
So, you need something more like a security camera icon?

**Comment by jouni** [comment]
I’m not seeing that kind of icon in FontAwesome, btw.

**Comment by arabedini** [comment]
@jouni the movie  icone in FontAwesome is like a security camera. it is enough if you add movie icon. if it's not close enough, please change the icon, so we can fill this gap for our project.
thanks

**Comment by jouni** [comment]
@arabedini, is that icon visible here: http://fontawesome.io/icons/

Also, I didn’t understand your request completely. There’s already the `movie` icon in Vaadin Icons (the one I linked in the repo earlier). We won’t be changing that icon to look like something else, at least not in the near future.

So, I’m not a bit confused, what is the gap that you have in your project?

**Comment by arabedini** [comment]
@jouni, at 11 Jul, when I add first comment, There is not movie at Vaadin Icons.

Thanks

Regards

**Comment by web-padawan** [comment]
>  There’s already the movie icon in Vaadin Icons (the one I linked in the repo earlier)

Closing per above comment.
