### ISSUE TITLE
Icon 'workplace' showing as double image

### ISSUE THREAD

**Issue by mpilone** [vaadin/vaadin-icons#41]
In the 8.1.0 Vaadin-Icons.woff file, the 'workplace' icon appears as a double image. From the best I can tell it is rendering both the hospital and workplace icon back to back. I used an online font viewer (http://torinak.com/font/lsfont.html) to verify that something looks odd at that point in the icon file. For now we're just avoiding that icon but it would be nice to have it available.

<img width="415" alt="contentdepot_portal" src="https://user-images.githubusercontent.com/3026098/30326720-6f24fac2-9797-11e7-911f-56f25ef74f74.png">

<img width="881" alt="vaadin-icons" src="https://user-images.githubusercontent.com/3026098/30326582-f70e8daa-9796-11e7-93c1-a1e360e971a6.png">

**Comment by jouni** [comment]
Thanks for the report! You’re correct, the exported SVG that is used for generating the font contains another icon outside the actual icon canvas, which becomes visible if the element you use the icons in is not using `overflow: hidden;`.

**Comment by jouni** [comment]
Would appreciate a PR for this one. You should be able to generate new font files by uploading the current SVG font to icomoon.io and exporting new web fonts with it. The most crucial part is making sure that the same unicode characters are used for the same icons as before, but I think those should map automatically with icomoon.

**Comment by mpilone** [comment]
We started looking into fixing this and found that in the 3.0 tag, the issue isn't present. However it is present in the 3.0.1 build (I can't find a corresponding tag) that Vaadin Framework is depending on. The latest 4.1.0 tag of Vaadin Icons also looks correct. 

So I think the issue is already fixed in the Vaadin Icons repo, but the 3.0.1 build that Vaadin Framework is using has the bug. It seems like the right fix would be to update the Vaadin Framework dependency to 4.1.0 and the issue would be resolved. I don't know your build process but it seems like the issue was introduced with the 3.0.1 build that doesn't match a tag in the icons repo.

**Comment by jouni** [comment]
It seems I’ve actually tried to fix this almost a year ago, in 7f2451a6ff325cf4819e07d14b41911a1e243eb2

I only fixed the web fonts back then, now I actually fixed the SVG source file as well in fb85ca5df136cd64b95cb54eae637c8277a8e70f

**Comment by web-padawan** [comment]
Closing as fixed per above comment.
