### ISSUE TITLE
The demo doesn't work in webcomponents.org

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-icons#43]
https://www.webcomponents.org/element/vaadin/vaadin-icons

There are two demo-links, but both of them open an empty dialog.
Chrome console reports some failed GET-requests with status 400.

The demo used to show all of the different `vaadin-icons`.

**Comment by yuriy-fix** [comment]
Dear Pekka,
Thank you you for this finding! We will try to fix the issue with demo-links as soon as possible.

**Comment by limonte** [comment]
Demos are working now, but this issue is still there:

> There are two demo-links

**Comment by Haprog** [comment]
This fix (also for duplicate demo link) is now included in [v4.2.2](https://github.com/vaadin/vaadin-icons/releases/tag/v4.2.2). Let's see if it works in https://www.webcomponents.org/element/vaadin/vaadin-icons once the new version is visible there.

**Comment by Haprog** [comment]
Looks like it worked fine. https://www.webcomponents.org/element/vaadin/vaadin-icons now shows 4.2.2 with only one Demo link and the demos still work.
