### ISSUE TITLE
The "All Icons" filter should use substring matching

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-icons#60]
The "All Icons" filter at https://vaadin.com/components/vaadin-icons/html-examples/icons-basic-demos probably matches using "starts-with". For example, typing "out" won't find the "sign-out" icon.

**Comment by web-padawan** [comment]
This is [fixed](https://github.com/vaadin/docs/blob/d4c7771eb04dcf3333d28193a5332bbb1279cebb/frontend/demo/foundation/icons-preview.ts#L81) in the new docs: https://vaadin.com/docs/latest/ds/foundation/icons/vaadin

![Screenshot 2021-05-03 at 10 50 59](https://user-images.githubusercontent.com/10589913/116852697-756bb280-abfd-11eb-86eb-cb225362016a.png)

We are not actively updating the Polymer 2 based live demos anymore, so I'm closing this issue.
