### ISSUE TITLE
Release vaadin-icons beta2 properly converted for P3

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-icons#64]
Feeback from the user in Slack: 

> `vaadin-icons.js` seems to have disappeared from the latest version of `@vaadin/vaadin-icons`

Also, "bower_components-1.x" folder has to be removed, the same as "bower-1.x.json"

**Comment by manolo** [comment]
Done: https://www.npmjs.com/package/@vaadin/vaadin-icons
