### ISSUE TITLE
Vaadin_V/H is outdated

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-icons#67]
The vaadin icons for our company logo still shows the old version (the V has serifs), the new one is sans serif.

Old: 
![image](https://user-images.githubusercontent.com/36725474/44704593-2bb98a00-aa9c-11e8-91e9-1e135131d3ac.png)

New:
![image](https://user-images.githubusercontent.com/36725474/44704578-20fef500-aa9c-11e8-907e-5f1748f3d70e.png)

**Comment by Haprog** [comment]
Looks like release [v4.1.4](https://github.com/vaadin/vaadin-icons/releases/tag/v4.1.4) updated the source files of the Vaadin logo (PNG, SVG and fonts) but didn't update the generated icon set file (`vaadin-icons.html`).

**Comment by Haprog** [comment]
This fix is now included in [v4.2.2](https://github.com/vaadin/vaadin-icons/releases/tag/v4.2.2)
