### ISSUE TITLE
Request additon of a switch on/off icon, this would be very useful

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-icons#68]
I implemented a BooleanButton / Switch similar to this:   
![image](https://user-images.githubusercontent.com/38694044/44849497-99131980-ac5a-11e8-853a-645e0a5a7366.png)

It is based on regular Vaadin "Button" Class, which uses Icons for On/Off state. However i'd like to have a switch icon within Vaadin. Currently i'm using external / custom resources for it. 

If vaadin would offer this i can avoid using them. I think some on-off icon is hardly needed.

Reference for Icon graphic: https://fontawesome.com/icons/toggle-on?style=solid&from=io

**Comment by web-padawan** [comment]
Hi, do you need the icon only or an actual component?
FYI there is a "toggle switch" theme in progress: vaadin/vaadin-checkbox#96

**Comment by masbaehr** [comment]
Ah nice to know! Thanks. So feel free to close it if you don't want to add this icon. I personally would like it, since it also offers the way to create custom switches which do not rely on the Checkbox class. But i think i can live with that.

Btw: Do you happen to know how i can add this theme to my Vaadin app? (So i can use it from Java

.getElement().setAttribute("theme", "switch");

**Comment by web-padawan** [comment]
Closing in favor of vaadin/vaadin-checkbox#90 per above comment.
