### ISSUE TITLE
Remove iron-icon import from vaadin-icons.html

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-icons#72]
Motivation based on the internal discussion:

> When doing lazy asynchronous imports, if you try to use some iconset before it was loaded/defined, it won't update `iron-icon` after the iconset is ready. We have a special bundle for icons on the website, with the import of `iron-icons` as the last one. But I cannot add `vaadin-icons` there for the reason above

We can still keep `iron-icon` as a dependency for backwards compatibility, and even have a separate file importing it as well, in order to avoid breaking change.

**Comment by jouni** [comment]
The same should be done for https://github.com/vaadin/vaadin-lumo-styles/blob/master/icons.html#L3, right?

**Comment by web-padawan** [comment]
Yes, I would prefer us having these aligned.

**Comment by Haprog** [comment]
I guess we could extract the actual iconset definition from e.g. `vaadin-icons.html` into a new file (e.g. `vaadin-iconset.html` or just `iconset.html`) which could be imported in `vaadin-icons.html` to keep `vaadin-icons.html` working as before without breaking changes, but this would make it possible to import just the new iconset file without getting the `iron-icon` dependency.

If we go with the name `iconset.html`, that file would contain:
```html
<link rel="import" href="../iron-iconset-svg/iron-iconset-svg.html">
<iron-iconset-svg name="vaadin" size="16">
...
</iron-iconset-svg>
```

And then `vaadin-icons.html` would basically just contain:
```html
<link rel="import" href="../iron-icon/iron-icon.html">
<link rel="import" href="iconset.html">
```
(plus some comments that the file now has)

Any comments @jouni @web-padawan?

And then similar change in `vaadin-lumo-styles` for the lumo icons.

**Comment by samie** [comment]
<img width="756" alt="Screenshot 2019-03-18 at 15 58 00" src="https://user-images.githubusercontent.com/991105/54535283-de006280-4996-11e9-9cce-d1571d188680.png">
