### ISSUE TITLE
Typo in icon name 'funcion'

### ISSUE THREAD

**Issue by edler-san** [vaadin/vaadin-icons#87]
The icon 'funcion' should be called 'function'.

See also vaadin/vaadin-icons-flow/issues/85 and vaadin/vaadin-icons-addon/issues/19

**Comment by alvarezguille** [comment]
Check https://github.com/vaadin/vaadin-icons-flow/issues/85#issuecomment-684760979

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/web-components/issues/311 where this will be handled.
