### ISSUE TITLE
Some icons have the title-tag included

### ISSUE THREAD

**Issue by whiteancient** [vaadin/vaadin-icons#94]
If the icons are included into a site (like Vaadin Flow is doing) the search engines are finding this wrong title instead of the title of the site. The image is a screenshot from google.

![Screenshot from Google](https://user-images.githubusercontent.com/10888998/100730215-11349080-33ca-11eb-93dc-185ac4af3e70.PNG)

**Comment by web-padawan** [comment]
Thanks for the issue. This is clearly a bug. These icons need to be updated:

https://github.com/vaadin/vaadin-icons/blob/e14c7131cee80c35a4e1b4bf5a6a6cb97de70a6a/iconset.html#L633-L634
